### ISSUE TITLE
Hello Master. @ xxxxxxx.png, which means the symbol @.

### ISSUE THREAD

**Issue by ghost** [kharij/Tekken-6-HD-Texture-Pack#2]
Hello, I would like to know what the @ symbol means in the directions of the textures. and what does the comma mean next to zero at the end.
I have also found the desktop.ini files, what are they for.
Can you explain the operation or route that PPSSPP does to read your textures?
Thanks in advance. God bless you always.

**Comment by kharij** [comment]
1. There is no "@" symbol in the textures. Can you provide an example? 
2. desktop.ini files are unimportant, and serve no purpose to the texture pack.
3. PPSSPP directly reads my textures.
